/* AVI EDITION for n-gon */
(()=>{'use strict';
const A=window.aviEdition=window.aviEdition||{weapon:1,field:null,nextFire:0,mouseFire:false,tech:{overcharge:false,massDriver:false,reactor:false,nanites:false},rockets:[],enemies:[],arena:[],message:''};
function hud(){if(document.getElementById('avi-hud'))return;const e=document.createElement('div');e.id='avi-hud';e.style.cssText='position:fixed;left:50%;top:10px;transform:translateX(-50%);z-index:2147483647;pointer-events:none;color:#fff;background:rgba(10,15,20,.94);border:2px solid #12d8ff;border-radius:8px;padding:9px 14px;min-width:370px;text-align:center;font:14px Arial';e.innerHTML='<b style="font-size:21px;color:#12d8ff">AVI EDITION</b><div id="avi-status">Starting...</div><small>1-4 Weapons | 5 Restore | Z/X/C Fields | 7/8/9/0 Tech | L/N/B</small><div id="avi-message"></div>';document.body.appendChild(e)}hud();
function boot(){if(window.aviEditionRuntime)return;if(typeof Matter==='undefined'||typeof player==='undefined'||typeof m==='undefined'||typeof simulation==='undefined'||typeof input==='undefined'||typeof engine==='undefined'){document.getElementById('avi-status').textContent='Waiting for n-gon...';setTimeout(boot,250);return}window.aviEditionRuntime=true;const V=Matter.Vector,B=Matter.Body,BD=Matter.Bodies,C=Matter.Composite;const cycle=()=>Number.isFinite(simulation.cycle)?simulation.cycle:0;const aim=()=>simulation.mouseInGame||player.position;const mobs=f=>{if(typeof mob!=='undefined'&&Array.isArray(mob))for(const w of mob)if(w&&w.alive&&w.position)f(w)};const d2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};const say=t=>{A.message=t;setTimeout(()=>{if(A.message===t)A.message=''},1500)};const dmg=(w,n)=>{try{if(typeof w.damage==='function')w.damage(n,true);else if(typeof w.health==='number')w.health-=n}catch(_){}};const custom=f=>A.enemies.forEach(e=>{if(e.alive&&e.body)f(e)});const kill=e=>{e.alive=false;try{C.remove(engine.world,e.body)}catch(_){}};
let oldFire=null,suppressed=false;function sync(){const gun=typeof b!=='undefined'?b:null;if(!gun||typeof gun.fire!=='function')return;if(A.weapon&&!suppressed){oldFire=gun.fire;gun.fire=function(){};suppressed=true}else if(!A.weapon&&suppressed){gun.fire=oldFire;suppressed=false}}
function beam(){const s=m.pos||player.position,t=aim(),dir=V.normalise(V.sub(t,s)),end=V.add(s,V.mult(dir,1600));mobs(w=>{const q=V.sub(w.position,s),along=V.dot(q,dir),side=Math.abs(V.cross(q,dir));if(along>0&&along<1600&&side<45)dmg(w,.8*(A.tech.overcharge?1.5:1))});custom(e=>{const q=V.sub(e.body.position,s),along=V.dot(q,dir),side=Math.abs(V.cross(q,dir));if(along>0&&along<1600&&side<55){e.health-=1;if(e.health<=0)kill(e)}});const x=innerWidth/2,y=innerHeight/2,mx=simulation.mouse.x,my=simulation.mouse.y,line=document.createElement('div');line.style.cssText='position:fixed;left:'+x+'px;top:'+y+'px;width:'+Math.hypot(mx-x,my-y)+'px;height:5px;background:#12d8ff;transform-origin:left center;transform:rotate('+Math.atan2(my-y,mx-x)+'rad);z-index:2147483646;pointer-events:none;box-shadow:0 0 12px #12d8ff';document.body.appendChild(line);setTimeout(()=>line.remove(),70)}
function rocket(){const s=m.pos||player.position,t=aim(),dir=V.normalise(V.sub(t,s)),body=BD.circle(s.x+dir.x*45,s.y+dir.y*45,11,{isSensor:true,frictionAir:.002});C.add(engine.world,body);B.setVelocity(body,V.mult(dir,28));A.rockets.push({body,life:90})}
function blast(p,r,n,force){mobs(w=>{const d=Math.sqrt(d2(w.position,p));if(d<r){const f=1-d/r;dmg(w,n*f);const u=V.normalise(V.sub(w.position,p));B.applyForce(w,w.position,V.mult(u,force*f*w.mass))}});custom(e=>{const d=Math.sqrt(d2(e.body.position,p));if(d<r){e.health-=n*(1-d/r);if(e.health<=0)kill(e)}})}
function gravity(){const p=aim();mobs(w=>{const d=Math.sqrt(d2(w.position,p));if(d<850){const u=V.normalise(V.sub(p,w.position));B.applyForce(w,w.position,V.mult(u,.004*(1-d/850)*w.mass))}});custom(e=>{const d=Math.sqrt(d2(e.body.position,p));if(d<850){const u=V.normalise(V.sub(p,e.body.position));B.applyForce(e.body,e.body.position,V.mult(u,.004*(1-d/850)*e.body.mass))}})}
function fire(){if(cycle()<A.nextFire)return;A.nextFire=cycle()+([0,5,18,8,14][A.weapon]||8)*(A.tech.reactor?.72:1);if(A.weapon===1)beam();else if(A.weapon===2)rocket();else if(A.weapon===3)gravity();else if(A.weapon===4)blast(aim(),300,.9,.05)}
function enemy(x,y,boss){const body=BD.polygon(x,y,boss?10:7,boss?55:25,{density:boss?.012:.006,restitution:.8,frictionAir:.01});C.add(engine.world,body);A.enemies.push({body,health:boss?80:10,boss:!!boss,alive:true})}function wave(){const p=player.position;for(let i=0;i<8;i++)enemy(p.x+(Math.random()-.5)*900,p.y+(Math.random()-.5)*500,false);say('CUSTOM WAVE')}function boss(){enemy(player.position.x+450,player.position.y-100,true);say('AVI BOSS')}function arena(){const p=player.position;for(const w of A.arena)try{C.remove(engine.world,w)}catch(_){}A.arena=[];[[p.x-700,p.y-500,1400,40],[p.x-700,p.y+460,1400,40],[p.x-700,p.y-500,40,1000],[p.x+660,p.y-500,40,1000]].forEach(q=>{const w=BD.rectangle(q[0]+q[2]/2,q[1]+q[3]/2,q[2],q[3],{isStatic:true});C.add(engine.world,w);A.arena.push(w)});for(let i=0;i<7;i++)enemy(p.x+(Math.random()-.5)*1000,p.y+(Math.random()-.5)*650,false);enemy(p.x,p.y-300,true);say('AVI ARENA + BOSS')}
function weapon(n){A.weapon=n;A.field=null;sync();say(n===0?'N-GON WEAPONS RESTORED':['','PLASMA RIFLE','ROCKET LAUNCHER','GRAVITY GUN','SINGULARITY SHOTGUN'][n])}function tech(n){A.tech[n]=!A.tech[n];say(n.toUpperCase()+': '+(A.tech[n]?'ON':'OFF'))}
window.addEventListener('mousedown',e=>{if(e.button===0)A.mouseFire=true});window.addEventListener('mouseup',e=>{if(e.button===0)A.mouseFire=false});window.addEventListener('blur',()=>A.mouseFire=false);window.addEventListener('keydown',e=>{if(e.repeat)return;const k=e.key.toLowerCase();if(k>='1'&&k<='4')weapon(+k);else if(k==='5')weapon(0);else if(k==='7')tech('overcharge');else if(k==='8')tech('massDriver');else if(k==='9')tech('reactor');else if(k==='0')tech('nanites');else if(k==='l')arena();else if(k==='n')wave();else if(k==='b')boss();else if('zxc'.includes(k))A.field=k});window.addEventListener('keyup',e=>{if('zxc'.includes(e.key.toLowerCase()))A.field=null});
function rockets(){for(let i=A.rockets.length-1;i>=0;i--){const r=A.rockets[i];if(!r.body){A.rockets.splice(i,1);continue}r.life--;if(r.life<=0){blast(r.body.position,190,1.5,.08);try{C.remove(engine.world,r.body)}catch(_){}A.rockets.splice(i,1)}}}function updateEnemies(){for(const e of A.enemies)if(e.alive){const q=V.sub(player.position,e.body.position),d=Math.hypot(q.x,q.y)||1;B.applyForce(e.body,e.body.position,V.mult(q,(e.boss?.0008:.0013)*e.body.mass/d))}A.enemies=A.enemies.filter(e=>e.alive)}
function hudUpdate(){const s=document.getElementById('avi-status');if(s)s.innerHTML='<b>Weapon:</b> '+['N-GON','PLASMA RIFLE','ROCKET LAUNCHER','GRAVITY GUN','SINGULARITY SHOTGUN'][A.weapon]+' &nbsp; <b>Field:</b> '+(A.field||'OFF').toUpperCase()+'<br><b>Tech:</b> '+(Object.keys(A.tech).filter(k=>A.tech[k]).join(', ')||'none');const q=document.getElementById('avi-message');if(q)q.textContent=A.message}
function tick(){try{sync();if(A.weapon&&(input.fire||A.mouseFire))fire();if(A.field==='z')mobs(w=>B.setVelocity(w,V.mult(w.velocity,.9)));if(A.field==='x')mobs(w=>{const d=Math.sqrt(d2(w.position,player.position));if(d<420){const u=V.normalise(V.sub(w.position,player.position));B.applyForce(w,w.position,V.mult(u,.004*w.mass))}});if(A.field==='c')blast(aim(),260,.18,.025);rockets();updateEnemies();hudUpdate()}catch(err){console.warn('Avi Edition:',err)}}say('AVI EDITION ONLINE');setInterval(tick,16)}boot()})();
